### PR TITLE
odc_public_update

### PR DESCRIPTION
**Pull request by issamdakir**
Hirarchy of the addon folders simplified
Registration simplified
Some code errors fixed
Added a control button, new operators to Models operations section and optimized code performance

### CODE REVIEW

**Comment by talmazov** [comment]
- on link, the object (not the parent) becomes hidden after operator - will fix
- on separate (i tried 3 joined objects), there is a 4th object created that is empty (model was not clean - nvm)
- center model - what if you center the model oriented towards the user?
- hollow model op button does not perform the cutback I implemented - agreed user should cutback bc the solid model may not always be made by our add-on and so the base cutback may be variable from what we pre-programmed - leaving as is
- solid+hollow op button, the cut back does not reflect base height input box - will fix

**Comment by issamdakir** [comment]
Link : hide child object option was added having in mind alignement + center models workflow also it will let you focus on preparing uper mesh and after you can hide parent and inhide child for lower mesh preparation if you think is not a good worflow i remove it from code and lat user decide maybe shoud add Hide deselected button and lock unlock button

**Comment by issamdakir** [comment]
On separate i use sepate by loose parts one of the joined meshs should not be clean

**Comment by issamdakir** [comment]
Center model i dont understand if you can try and give me feedback of the issue

**Comment by issamdakir** [comment]
Cutting is not yet implemented in separate hollow button the resulting object name is obj_name_hollow not obj_name_hollow_base

**Comment by issamdakir** [comment]
i closed the PR of yesterday

**Comment by talmazov** [comment]
Thanks!

**Pull request closed without merging**
